baseURL = 'https://jyksnw.com/'
title = 'Jason Snow'
languageCode = 'en-us'
theme = 'soho'
paginate = 10
summarylength = 10

enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true

disqusShortname = 'jason-snow'

[params]
author = "Jason Snow"
copyright = "Jason Snow"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
mainSections = ["posts"]
images = ["images/profile.png"]
profilePicture = "images/profile.png"
themeColor = "#515A5A"
builtWith = true

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jyksnw/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/jyksnw"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/jyksnw"

[[params.socialIcons]]
icon = "fa-at"
title = "Email"
url = "mailto:jason@jyksnw.com"

[menu]

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 100

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 300

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[markup]

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
